# Generated by Django 3.1.2 on 2020-10-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date_time',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 17, 15, 54, 353413)),
        ),
    ]
