# Generated by Django 3.1.2 on 2020-10-17 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201017_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 17, 19, 27, 777139)),
        ),
    ]
