# Generated by Django 3.1.2 on 2020-10-18 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201017_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 5, 5, 18, 141885)),
        ),
    ]
