# Generated by Django 3.1.2 on 2020-10-21 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201020_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 5, 51, 29, 342504)),
        ),
    ]
